on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Build
        run: |
          dart pub get
          dart format --output=none --set-exit-if-changed .
          dart analyze
          dart test --reporter json > dart-test-example.json

      - name: Collect events
        uses: buildnote/action@main
        env:
          BUILDNOTE_API_KEY: ${{ secrets.BUILDNOTE_API_KEY }}
          BUILDNOTE_GITHUB_JOB_NAME: build-and-test
          BUILDNOTE_GITHUB_TOKEN: ${{secrets.BUILDNOTE_GITHUB_TOKEN}}
        if: always()