on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BUILDNOTE_GITHUB_JOB_NAME: build-and-test
      BUILDNOTE_API_KEY: ${{ secrets.BUILDNOTE_API_KEY }}
      BUILDNOTE_GITHUB_TOKEN: ${{secrets.BUILDNOTE_GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Collect events
        uses: buildnote/action@main
        with:
          installOnly: 'true'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test --reporter json > dart-test-example.json

      - name: Collect tests
        run: buildnote collect --enabled dart files
        if: always()

      - name: Collect GitHub events
        run: buildnote collect --enabled githubAction
        if: always()
